site_name: 'python-app-3'
site_description: 'Main documentation for the python-app-3'
repo_url: https://github.com/ben14132/python-app-3
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'index.md'